name: gesit
description: "Projek Aplikasi Stor Sampah berbasis IOT APP MOBILE."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_database: ^10.5.4
  cloud_firestore: ^4.16.1
  provider: ^6.1.2
  percent_indicator: ^4.2.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  google_fonts: ^6.2.1
  geolocator: ^7.1.0
  http: ^1.2.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
