name: gesit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_database: ^10.5.4
  cloud_firestore: ^4.16.1
  provider: ^6.1.2
  go_router: ^14.1.3
  percent_indicator: ^4.2.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-BoldItalic.ttf
  #         weight: 700
  #         style: italic
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Poppins-LightItalic.ttf
  #         weight: 300
  #         style: italic
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-MediumItalic.ttf
  #         weight: 500
  #         style: italic
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
  #         weight: 600
  #         style: italic
  #       - asset: assets/fonts/Poppins-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
  #         weight: 800
  #         style: italic